name: mycanister
services:
  myconister:
    image: biconomy/mycanister:latest
    container_name: mycanister
    # restart: unless-stopped
    tty: true
    volumes:
      - .:/canister/predit
      - .config:/root/.config
      # - /Users/tao/sources/icp/examples/rust:/canister/examples
    ports:
      - "4943:4943"
      - "5555:5555"
    command: ["tail","-f","predit/logs/dfx.log"]