name: mycanister
services:
  myconister:
    build:
      context: .
      dockerfile: canister.Dockerfile  
    container_name: mycanister
    restart: unless-stopped
    tty: true
    volumes:
      - .:/canister
    ports:
      - "4943:4943"
      - "39939:39939"
    # command: ["dfx","start","--host","0.0.0.0:4943","--force"]