name: mycanister
services:
  myconister:
    # build:
    #   context: .
    #   dockerfile: canister.Dockerfile  
    image: biconomy/mycanister:latest
    container_name: mycanister
    # restart: unless-stopped
    tty: true
    volumes:
      - .:/canister/predit
    ports:
      - "4943:4943"
      - "39939:39939"
    command: ["dfx","start","--clean","--host","0.0.0.0:4943","--force"]